baseURL: 'http://picoe.ca/'
languageCode: "en-us"
title: 'Picoe Software Solutions'
theme: "ananke"
# theme: "syna"
sectionPagesMenu: "main"
params:
  mainSections: [news]
  background_color_class: bg-blue
  

markup:
  goldmark:
    renderer:
      unsafe: true